name: Workflow for HIT 1

on:
    push:
        branches: ['main']
        paths: ['TP1/ej1/**']
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Run Commands
              run: |
                  echo "ğŸ‘‹ğŸ¼ Hello world!"
                  echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
                  echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
                  echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    # build-and-push:
    #     name: Build and Push Docker Image
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2

    #         - name: Login to Docker Hub
    #           uses: docker/login-action@v2
    #           with:
    #               username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #               password: ${{ secrets.DOCKER_HUB_TOKEN }}

    #         - name: Build Docker image
    #           run: |
    #               docker build -t your-docker-username/tcp-server-1:latest .

    #         - name: Push Docker image to Docker Hub
    #           run: |
    #               docker push your-docker-username/tcp-server-1:latest
